# How far to jump on press.
# Set to 0 to disable seeking and use pure hold-to-fast-forward.
seek_distance=5

# Playback speed modifier, applied once every speed_interval until cap is reached.
speed_increase=0.1
speed_decrease=0.1

# At what interval to apply speed modifiers.
speed_interval=0.05

# Playback speed cap.
speed_cap=2

# Playback speed cap when subtitles are displayed.
# Use "no" for same as speed_cap.
subs_speed_cap=1.6

# Multiply current speed by modifier before adjustment.
# For exponential speedup, use much lower values, for example:
# speed_increase=0.05
# speed_decrease=0.025
multiply_modifier=no

# Show current speed on the OSD, or flash speed if using uosc.
show_speed=yes

# Show current speed on the OSD when toggled.
show_speed_toggled=yes

# Show current speed on the OSD when speeding up toward a target time.
show_speed_target=no

# Show seek actions on the OSD, or flash timeline if using uosc.
show_seek=yes

# Look ahead for smoother transition when subs_speed_cap is set.
lookahead=no
